create wiki and example of a file
IgalKolihman/idf.officers.tools pull request #1
Opened 2022-01-10 19:50 UTC by solm11

2022-01-12 07:05 UTC, IgalKolihman requested changes
First review, first workflow insights

2022-01-12 07:05 UTC, IgalKolihman commented on wiki/1/1.3.md
> +##### 1.3 **סמלים לאומיים**
Stuff like this better be formatted to HTML tags (<h#>)

2022-01-12 07:05 UTC, IgalKolihman commented on wiki/1/1.3.md
> +﻿
This whole file formatted weirdly, comparing to the previous two.

Format it again, make sure that titles are not represented with #, but with <h#>

2022-01-12 08:23 UTC, solm11 commented on wiki/1/1.2.md
> +במדינת ישראל מתקיימת הן המערכת הפורמלית (מוסדות שלטון דמוקרטיים, בחירות, חילופי שלטון) והן המערכת התרבותית (שוויון, אפליה מתקנת, מדיניות רווחה) . אחד מן ההיבטים הפורמליים החשובים ביותר הוא עקרון הפרד
sounds great! :)

2022-01-12 12:59 UTC, solm11 commented on wiki/1/1.2.md
> +בישראל ,הכנסת מהווה את הרשות המחוקקת של המדינה .מכהנים בה 120 חברים, הנבחרים על־ידי הציבור אחת לארבע שנים (בהנחה שהבחירות אינן מוקדמות.) מקור השם "כנסת" הוא בכנסת הגדולה, אשר התכנסה בירושלים בימי הבי
dont understand the problem.

2022-01-15 10:48 UTC, IgalKolihman requested changes

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.1.md
> +</p>
you didn't separate the paragraph content from the `<p>` tags
```suggestion
<p dir="rtl">
מייסדיה של ישראל שאפו להקים מדינה המקיימת תרבות ומשטר דמוקרטי ואשר אופייה ותרבותה הלאומיים יהיו מושתתים על היהדות. הם לא ראו בשני עקרונות אלו, עקרונות סותרים; אדרבה, על- פי מגילת העצמאות הם נובעים זה מזה: "מדינת ישראל... תהא מושתתת על יסודות החירות, הצדק והשלום – לאור חזונם של נביאי ישראל". סקרי דעת קהל ומחקרים מלמדים שהגדרה זו מקובלת על רובו המכריע של הציבור הישראלי, אולם לצד הסכמה זו מתקיים בישראל דיון ארוך שנים כיצד על היסודות היהודיים והדמוקרטיים לבוא לידי ביטוי.
</p>
```

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.1.md
> +<p dir="rtl"><b>השופט חיים כהן (1911-2002) </b>סבר כי יש למצוא את שורשי הדמוקרטיה ביהדות ובמשפט לעצב ולבנות העברי; הוא ראה בצמד המילים "יהודית" ו"-דמוקרטית," מושג אחד וגרס כי יש "יהדות שהיא דמוקרטית
and make the text is still over 120 chars in a line

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.2.md
> +•     מערכת פורמלית-מוסדית הכוללת תהליכים מוסכמים הקיימים בכל משטר דמוקרטי ובאמצעותם מתממש עקרון ריבונות העם: הכרעת הרוב, קיומה של אופוזיציה ובחירות חופשיות ושוויוניות.
better if it was `<li>` and not `•     `

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.1.md
> +</p>
remove the `<p>` tags for content inside `h#` titles

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.2.md
> +1.2.1 הרשות המחוקקת: כנסת ישראל</p>
when you upload your changes, review the looks of it in the preview. all the titles do not present correctly.

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.2.md
> +שהוא "חוקתי," קרי, אינו סותר את חוקי היסוד ואינו סותר את הגדרתה של ישראל כמדינה יהודית ודמוקרטית. הבקרה על עבודת הממשלה נעשית באמצעות היכולת להצביע בה" אי-אמון" ובכך לגרום לנפילתה, באמצעות היכולת לשא
this is an extremely long paragraph, separate into smaller paragraphs.

2022-01-15 10:48 UTC, IgalKolihman commented on wiki/1/1.3.md
> +\* טבח כפר קאסם נידון בפרק נפרד בהמשך.
replace `\*` with something else that will still gives the same meaning. maybe replace to `[*]`

2022-01-15 11:15 UTC, IgalKolihman commented on wiki/1/1.1.md
> +<p dir="rtl"><b>השופט חיים כהן (1911-2002) </b>סבר כי יש למצוא את שורשי הדמוקרטיה ביהדות ובמשפט לעצב ולבנות העברי; הוא ראה בצמד המילים "יהודית" ו"-דמוקרטית," מושג אחד וגרס כי יש "יהדות שהיא דמוקרטית
forget about 120 chars in a line.

2022-01-15 11:34 UTC, merged